### ISSUE TITLE
Docker : Error 401

### ISSUE THREAD

**Issue by Spartan17** [diegogarciadev/android_snipeitapp_config#10]
Hi Diego, 

First, thanks for all the work on this app. 

I've set up a small docker container. All Snipe-IT features work. 

I've created the API key on the web interface, edited the php file and used docker exec to copy it to /var/www/html/public. No matter the method, i get a 401: Unauthorized error. 

I've checked permissions and found out the php file was owned by root and not by docker, so i did a quick chown. No change. 

Anything i'm not doing right? 

Thanks

**Comment by diegogarciadev** [comment]
Hello, have you checked the responses at #1 ?

Maybe it can help you
