### ISSUE TITLE
Certificate error when I try to configure my own hosting

### ISSUE THREAD

**Issue by wysird** [diegogarciadev/android_snipeitapp_config#12]
**Describe the bug**
App won't accept the certificate provided by my server.

**To Reproduce**
1. Go to 'Settings' (via Cog in the top right)
2. Click on "Snip-IT server address"
3. Enter my local server address
4. Click 'CONFIGURE APP' (at the bottom)
5. Get error "Error -1: java.security.cert.CertPathValidatorException: Trust ..."

**Expected behavior**
Should accept the URL and connect to my internal server.

**Screenshots**
![Error as it appears in the app](https://user-images.githubusercontent.com/48929021/102823444-d0c9a080-43d2-11eb-9f37-9641896c76cd.jpeg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9
 - OS: Android 10
 - Version: 0.5.5-SnipeIT

**Additional context**
- I'm hosting the server internally on my LAN.
- The certificate provided is signed by Let's Encrypt
- I have installed all Let's Encrypt CAs and intermediates into the OS certificate manager
- I am able to access the server web GUI via any browser installed on the same device
- Server is hosted behind a reverse proxy

**Comment by wysird** [comment]
Still an issue, please leave this open. I can contribute if necessary

**Comment by diegogarciadev** [comment]
Hello, app take root certificates from device. Google doesn't allow to upload applications that allows untrusted crertificates because it could be a security problem...

Can you try without https?

**Comment by wysird** [comment]
I had installed my local CA root and intermediate in the OS but I was still getting the error above.

I seem to have now resolved the issue by purchasing the domain and requesting certificates via let's encrypt.

They are now publicly signed certificates, which is now allowing me to connect via https.

Http is not an option for me.
