### ISSUE TITLE
Not all users available for checkout

### ISSUE THREAD

**Issue by tuomaskalliomaki** [diegogarciadev/android_snipeitapp_config#14]
Hi,

Thank you for a great app.

Unfortunately I have ran into a problem in it.

_**Describe the bug**_

When trying to checkout a device to a user, 'User' -field does not return all users from the Snipe-IT's user database.

It might be related to a limitation of 500 items returned by the Snipe-IT API.

_**To Reproduce**_

1. Go to 'Assets Manager App'
2. Click on 'CHECKOUT' icon
3. Select an asset by scanning a barcode
4. Click on 'CHECKOUT (USER)'
5. Click on 'User -field'
6. Write few characters to filter out the user list
7. Not all users available on the filtered list

_**Expected behavior**_

There should be all users available on the list that are existed in the Snipe-IT 'People' -view.

_**Screenshots**_

![image](https://user-images.githubusercontent.com/55955342/111304114-068ec600-865e-11eb-83e9-0203317eaa9d.png)

_**Smartphone**_

 - Device: Samsung A41 (SM-415F/DSN)
 - OS: Android 10

**Comment by PetriAsi** [comment]
I have this same problem.

**Comment by gladverwast** [comment]
I have also come across this issue, our environment has roughly 15000 users at the moment so 500 limit makes the checkout feature unusable :(

**Comment by diegogarciadev** [comment]
I will check this issue, I have to check if I can solve it...

**Comment by PetriAsi** [comment]
Great, I believe that this issue with api, as snipe it api limits returned objects count to 500. So app using api have to do results paging by it self.

**Comment by diegogarciadev** [comment]
The issue has been solved. You will get an update in the following days. Thank you and sorry for the delay. 

Remember that you can help me to keep de develop of this app contributing with a cup of coffee : [https://paypal.me/diegogarciadev](https://paypal.me/diegogarciadev)

**Comment by PetriAsi** [comment]
Thanks! enjoy your coffee, sent you some.

**Comment by diegogarciadev** [comment]
> Thanks! enjoy your coffee, sent you some.

Thank you!
