### ISSUE TITLE
Assets creation

### ISSUE THREAD

**Issue by Doneven2012** [diegogarciadev/android_snipeitapp_config#16]
**Is your feature request related to a problem? Please describe.**
Somewhat. The app seems like it could be very useful for existing installations. The problem is for new ones, like in my case where no inventory exists for certain types of devices. It would be great to be able to create an asset and/or category, model, similar with the app.

**Describe the solution you'd like**
Having not used SnipeIT's API myself, I don't know how easy or difficult this would be. But adding a button to add an asset which would behave like when you create an asset on the web interface would be great. With or without the ability to add models, categories, etc. 

**Additional context**

**Comment by diegogarciadev** [comment]
I have to work in this feature

**Comment by diegogarciadev** [comment]
A new release is on progress, so the feature is arriving to the app.

Remember that you can help me to keep de develop of this app contributing with a cup of coffee : https://paypal.me/diegogarciadev
