### ISSUE TITLE
Quotation marks change to HTML entity

### ISSUE THREAD

**Issue by Cautious-Software701** [diegogarciadev/android_snipeitapp_config#17]
**Describe the bug**
When you checkout an asset with a quotation mark in the 'Asset Name' field, such as '24" Monitor' it changes to '24`&quot;` Monitor'.

**To Reproduce**
1. Click on Checkout user
2. Find asset to checkout
3. Click on 'CHECKOUT (USER)'
4. See error in 'Asset Name' field

**Expected behavior**
The quotation mark should be shown, and not he HTML entity code.

**Smartphone (please complete the following information):**
 - Device: Samsung S10
 - OS: Android 11
 - Version: 0.5.5-SnipeIT

**Comment by diegogarciadev** [comment]
I have to check this issue

**Comment by diegogarciadev** [comment]
The issue has been solved. It will be available in next release.
