### ISSUE TITLE
Open source snipeit app

### ISSUE THREAD

**Issue by PetriAsi** [diegogarciadev/android_snipeitapp_config#19]
Open sourcing snipe it app would be awesome and useful to many users.
I would be great if you could evaluate possibility to  open code base of snipe it app to public.

**Comment by diegogarciadev** [comment]
From the moment is not an option for me, sorry

**Comment by PetriAsi** [comment]
Hope you remember that open source does not mean free. But this is ok too.

**Comment by diegogarciadev** [comment]
The app is free now, but open sourcing the app will cause that there would be another copies working and each of them has different functionalities

**Comment by PetriAsi** [comment]
Could be, but your project started that all, that would be also something. And if you look how Snipe is doing, whole Snipe it is free , and still she and whole company is making living from it. There's lots of forks of snipe it and even whole whole docker support in snipe-it is just for community, it's not selled feature. Forks does not hurt if you can accept nice pull requests and keep you users supported. For us it was easy to choose snipe-it hosted version.

Open sourcing could  really help you project grow and   get new customers.  Just plan support model for commercial app. Those
who are not willing to pay commercial app and are forking, will not ever give anything to you. no matter how you do. But there more to what you can win with active user community , more users and  more customers.  For me it's hard to see anything to lose by going open source. 

What ever you choose your own reasons I'm fine with that and hope that it's going well for you. But if you ever gonna open source it I could help translating it to Finnish. And maybe offer some pull request also. :)
