### ISSUE TITLE
Can't connect my server with http

### ISSUE THREAD

**Issue by Thecloudff7** [diegogarciadev/android_snipeitapp_config#20]
**Describe the bug**
When I try to connect via http I receive the error "Clear text HTTP traffic for inv.servicios.local not permitted" and when I try to connect via https I receive the error "Trust anchor for certification path not found" do you think it can be solved? My ca is private (inv.servicios.local)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 93.0

**Smartphone (please complete the following information):**
 - Device: Motorola G10
 - OS: Android 10
 - Browser App(?)

**Comment by diegogarciadev** [comment]
Can you tell me what is the version you have installed? You can check it in app settings.

Do you have your certificate intalled on the device?

Regards.

**Comment by Thecloudff7** [comment]
Version 0.6.6-SnipeIT

And yes, I have installed cert Wi-fi on andriod.

Can I connect with http?

**Comment by diegogarciadev** [comment]
Yes, you can use http. But it should work with https after install certificates.

Regards.

**Comment by Thecloudff7** [comment]
No, still with the same error, and the certificate is installed
![http](https://user-images.githubusercontent.com/65539896/133415539-64ff599b-9766-4eef-bfee-533e76409b5e.png)
![https](https://user-images.githubusercontent.com/65539896/133415541-9f34208c-116e-4786-b6f8-fbc4a850eca3.png)

**Comment by diegogarciadev** [comment]
Please, update the app to last version 0.6.8

**Comment by Thecloudff7** [comment]
wow! now works, thanks!

**Comment by diegogarciadev** [comment]
Perfect!

Remember that you can help me to keep de develop of this app contributing with a cup of coffee : https://paypal.me/diegogarciadev
