### ISSUE TITLE
(solved) Error 401: Unauthorized problem

### ISSUE THREAD

**Issue by wkulesza** [diegogarciadev/android_snipeitapp_config#22]
**Describe the bug**
Can't configure the app, as after providing url and uploading edited config file, i get "Error 401: Unauthorized" when clicking Configure app.

**To Reproduce**
1. Install and configure Snipe It - the docker version
2. Edit, provide api-key (either new or use the one created when installing snipeit) and upload the snipeitapp_config.php file using docker cp snipeitapp_config.php snipeit:/var/www/html/public
3. open up Android app, add the snipe-it server address and hit configure app
4. you will see the red error on app saying: Error 401: Unauthorized

**Expected behavior**
App should respond with: "App configured!!"

**Desktop (please complete the following information):**
 - OS: Linux/docker

**Smartphone (please complete the following information):**
 - Huawei Android 9
 - - snipeit app 0.6.8-SnipeIT

EDIT: Mark as solved - it wasn't clear that i need to create a new API key in the SnipeIT itself first and use that to authorize myself.

**Comment by diegogarciadev** [comment]
Ok, I will close the issue
