### ISSUE TITLE
App doesn't work properly for audit with QR barcode labels generated in Snipe-IT

### ISSUE THREAD

**Issue by localzuk** [diegogarciadev/android_snipeitapp_config#23]
**Describe the bug**
We use barcode labels produced by Snipe-IT. The QR codes it produces are a link directly to the asset in the system. The app works OK to bring up the asset on screen, but tapping the Audit button returns an error.

**To Reproduce**
1. Print an asset label from Snipe-IT with a QR code
2. Scan that QR code into the app in Audit
3. See the record for the item display OK
4. Tap the Audit button
5. See an error saying the asset tag can't be found.

**Expected behavior**
Audit should audit the item, same as if the barcode was just the asset ID number

**Comment by diegogarciadev** [comment]
Hello, I'm working on a fix, It would be available soon. Regards.

**Comment by diegogarciadev** [comment]
The issue has been solved. You will get an update in the following hours. Thank you and sorry for the delay.

Remember that you can help me to keep de develop of this app contributing with a cup of coffee : https://paypal.me/diegogarciadev
