### ISSUE TITLE
More than one user?

### ISSUE THREAD

**Issue by wkulesza** [diegogarciadev/android_snipeitapp_config#24]
Is it possible for more than one user to use this app ?
Each user must have a unique API key, set int snipeitapp_config.php ?
If not, we can use the same one - and have several users use this at the same time ?

**Comment by diegogarciadev** [comment]
Hello,

You have to create api key in one user, then modify the php file, then configure the device. You have to follow this three steps as many users you want. You can also write the api key directly in the app without editing the php file.

Regards.
