### ISSUE TITLE
asset to asset  checkout

### ISSUE THREAD

**Issue by freddag** [diegogarciadev/android_snipeitapp_config#25]
**Is your feature request related to a problem? Please describe.**
Would be great to have support to check out assets to assets as this would be a great feature to help mange more complex assets

**Describe the solution you'd like**
Would be great to have a toggle/select option to do this as the API has support for checkout_to_type assigned_asset

**Describe alternatives you've considered**
Currently quite happy using the web interface as still building the database

**Additional context**
Love how simple the app is and could have some very interesting items added in the future.

**Comment by diegogarciadev** [comment]
Working on it... keep connected... ;)

**Comment by diegogarciadev** [comment]
The issue has been solved.

Remember that you can help me to keep de develop of this app contributing with a cup of coffee : https://paypal.me/diegogarciadev
