### ISSUE TITLE
Serial Number - Creating new asset

### ISSUE THREAD

**Issue by lhicks95** [diegogarciadev/android_snipeitapp_config#27]
**Is your feature request related to a problem? Please describe.**
When creating assets in the app, there's no field for a serial number. I have this installed on an android device with a barcode reader attachment. It'd be so much more efficient to input or scan the barcode on the device for the serial number.

**Describe the solution you'd like**
A field which allows text input for the serial number when creating a new asset.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by diegogarciadev** [comment]
The issue has been solved. You will get an update in the following hours.

Remember that you can help me to keep de develop of this app contributing with a cup of coffee : https://paypal.me/diegogarciadev
