### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jdtinsley88** [diegogarciadev/android_snipeitapp_config#3]
What do I need to do for multiple users?  Generate API key for each user and copy and paste into that php file?

**Comment by diegogarciadev** [comment]
You can have one key for each user or the same for all. You hace to
configure one by one editing the config file.

Regards.

**Comment by jdtinsley88** [comment]
When I use http://ipofsnipeitserver/

I get "Error-1 : Unexpected char 0x0a at 7 in header value:

Bearer ...

If I just use ipofsnipeitserver without the http portion, I get "Error 
-1 : no protocol: ipofsnipeitserver/snipeitapp_config.php

I am not using https because this is just an internal web server that 
only a few users access.

**Comment by diegogarciadev** [comment]
0x0a is a new line char, review that you don't have spaces in api key in php config file

**Comment by diegogarciadev** [comment]
Have you solve the problem?
