### ISSUE TITLE
Error 401: Unauthorized 

### ISSUE THREAD

**Issue by sillybowler** [diegogarciadev/android_snipeitapp_config#30]
Is there anything that can fix this?

**Comment by diegogarciadev** [comment]
Can you try this:

401 Unauthorized Error on API calls
API tokens default to being valid for 40 years. If you run into this issue, you are most likely running a 32-bit version of PHP (which, why?). To work around this, in your .env, set API_TOKEN_EXPIRATION_YEARS to a smaller number, like 10 years.

**Comment by LJGxuyaohui** [comment]
I set API_TOKEN_EXPIRATION_YEARS to 10 years，however, 401 unauthorized error on API calls is still reported，can you help me？

**Comment by LJGxuyaohui** [comment]
> Can you try this:
> 
> 401 Unauthorized Error on API calls API tokens default to being valid for 40 years. If you run into this issue, you are most likely running a 32-bit version of PHP (which, why?). To work around this, in your .env, set API_TOKEN_EXPIRATION_YEARS to a smaller number, like 10 years.

I set API_TOKEN_EXPIRATION_YEARS to 10 years，however, 401 unauthorized error on API calls is still reported，can you help me？

**Comment by LJGxuyaohui** [comment]
> 

I did it, I messed up the API, it was a long API,

**Comment by wharden-qa** [comment]
I'm trying to evaluate Snipe-IT for my company but I can't seem to get the app to connect; getting the same 401: Unauthorized error.

Local installation for testing, using the IP address and not a domain.
Checked PHP version (7.4 from amd64 ubuntu focal repo) and tried setting API_TOKEN_EXPIRATION_YEARS to 10 in .env.
Saved the API string to file and copy/pasted to app for alternate method to ensure no typos.

Same error every time.

Ideas?

**Comment by flinthamm** [comment]
Despite the app working at one point, I now cannot get both the latest Beta or the stable to work as it just returns a 401 error? If I use the local URL and use the alt method by entering the API key direct in the App it fails with this error. If I make the snipeitapp_config.php file available in the public folder it also fails with 401. The only way I can get it to work is by typing the local URL (no certificate with verification disabled in App settings) forward slash and then the snipeitapp_config,php at which point it states "App configured!" in green and returns to settings. However, the app then fails to work at all, if you try any queries, it just flashes a screen and eventually crashes.
I've tried reinstalling, clearing data, setting up as described above and then removing the snipeitapp_config.php from the url but it then just fails. 
It such a shame and I'm hoping this might still be developed. Would be happy to pay, if there was a clear development road map and the app was reliable even with basic CRUD functionality.
Hopefully this repository is still being monitored?

**Comment by justinkoby** [comment]
Instructions that I found were unclear. I had to go into Snipe, click on my name in the upper right, and generate an API key there. Then I used that key in the mobile app under the alternate config option.

**Comment by diegogarciadev** [comment]
> Despite the app working at one point, I now cannot get both the latest Beta or the stable to work as it just returns a 401 error? If I use the local URL and use the alt method by entering the API key direct in the App it fails with this error. If I make the snipeitapp_config.php file available in the public folder it also fails with 401. The only way I can get it to work is by typing the local URL (no certificate with verification disabled in App settings) forward slash and then the snipeitapp_config,php at which point it states "App configured!" in green and returns to settings. However, the app then fails to work at all, if you try any queries, it just flashes a screen and eventually crashes. I've tried reinstalling, clearing data, setting up as described above and then removing the snipeitapp_config.php from the url but it then just fails. It such a shame and I'm hoping this might still be developed. Would be happy to pay, if there was a clear development road map and the app was reliable even with basic CRUD functionality. Hopefully this repository is still being monitored?

Hi, there is no login functionality in the API, so this is the only way we have to connect to the API. I asked to the application developers to implement something but I didn't get any feedback. My application only uses the API to make changes so I don't have any chance to modify the API. Regards.

**Comment by diegogarciadev** [comment]
No clear error here
