### ISSUE TITLE
snipeitapp_config.php not found in server

### ISSUE THREAD

**Issue by Shain-Allen** [diegogarciadev/android_snipeitapp_config#31]
I have put the snipeitapp_config.php file into the root of my snipeit folder (also contains the .env file that houses my API key) but the app is still unable to locate the snipeitapp_config.php file.

I also attempted to configure via the alternate method but just got an error 401: unauthorized. API_token_expiration is set to 15

I am also self-hosting via nginx and have restarted that service to no change.

also, attempting to go to the file on the server via my web browser leads to a 404

**Comment by LJGxuyaohui** [comment]
Have you solved it?

**Comment by Shain-Allen** [comment]
unfortunately no, but it might have something to do with me using Virtual box which appears to have made my VM go a little wacky. I did end up getting another instance spun up in proxmox but I have yet to get time to try this again on that instance.

**Comment by Shain-Allen** [comment]
So I solved this cause I was dumb and missed the part about putting the file in the Public directory but now I am just getting error 401: unauthorized

**Comment by LJGxuyaohui** [comment]
> So I solved this cause I was dumb and missed the part about putting the file in the Public directory but now I am just getting error 401: unauthorized
I found a way to configure the success, but can not enter any operation, just configuration success, hope the author can have a detailed tutorial.
I also put the snipeitapp_config.php file in the public folder and set the address... /pubulic/snipeitapp_config.php,

I don't know how to upload screenshots, otherwise I can give you screenshots for you to see, but I don't know how to use it later, there should be something wrong with my configuration, how can I contact you?

**Comment by LJGxuyaohui** [comment]
> > So I solved this cause I was dumb and missed the part about putting the file in the Public directory but now I am just getting error 401: unauthorized
> > I found a way to configure the success, but can not enter any operation, just configuration success, hope the author can have a detailed tutorial.
> > I also put the snipeitapp_config.php file in the public folder and set the address... /pubulic/snipeitapp_config.php,
> 
> I don't know how to upload screenshots, otherwise I can give you screenshots for you to see, but I don't know how to use it later, there should be something wrong with my configuration, how can I contact you?

I did it, I messed up the API, it was a long API,Maybe you should be the reason, nod like position >Manage API Keys and create an API with very long values. My email is xuyaohui112@outlook.com, if you want to see screenshots, you can email me.

**Comment by Datinhkhach** [comment]
> 

Hi @LJGxuyaohui , I have same issue and now im suck at "**error 401: unauthorized**" , can you explain how to fix this. thanks you very much .

**Comment by diegogarciadev** [comment]
Please, check #1 to solve the issue
