### ISSUE TITLE
Retrict access for some logged in users

### ISSUE THREAD

**Issue by narfACS** [diegogarciadev/android_snipeitapp_config#33]
**Is your feature request related to a problem? Please describe.**
We don't want every employee to be able to edit or create assets, just the admin users

**Describe the solution you'd like**
Login for all users to be able to restrict some users from only check-in and checkout assets and nothing more.

**Describe alternatives you've considered**
N/A

**Additional context**
Just a login screen for each user on Snipe-it access.

**Comment by diegogarciadev** [comment]
Hello,

The API doesn't allow to login with user or password, so there are no way to change the user for the application. 

Sorry about that, I asked for that in the app repo and I had no answer...
