### ISSUE TITLE
Value <!-- of type java.lang.string cannot be converted to JSONObject

### ISSUE THREAD

**Issue by Robbindj** [diegogarciadev/android_snipeitapp_config#34]
**Describe the bug**
Error when connecting to Snipeit Server: 
Value <!-- of type java.lang.string cannot be converted to JSONObject after following instructions

snipeitapp_config.php is accessible
No error coces when requesting the page on pc
api code was generated in snipeit, and added in

**To Reproduce**
1. Go to Settings
2. Select Snipe-IT Server Address
3. Enter server address correctly
4. Press Configure
5. Error shows

**Expected behavior**
No error code

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Samsung A52s
 - OS: Android version: 12

**Additional context**
Manually adding in the API code appears to not test anything and will just be accepted, but nothing shows.

**Comment by diegogarciadev** [comment]
Hello, I'd like to figure out this issue, can you please give me more details and send me ans screenshot of the issue. Thanks
