### ISSUE TITLE
snipeitapp_config.php not found in server, review previous steps

### ISSUE THREAD

**Issue by MariusTaz** [diegogarciadev/android_snipeitapp_config#35]
I have put the snipeitapp_config.php file into the root of my snipeit folder but the app is still unable to locate the snipeitapp_config.php file. However I can access the file via web path and it return the API KEY text inserted in the file.

I also attempted to configure via the alternate method and I've got exactly the same error.

However if i add the filename in app settings like: https://snipeit.[MYSERVER].com/snipeitapp_config.php the app manages to configure, but afterwards when i try to load models or manufecturers for example it crashes.

Please advise. Thank you!

**Comment by kunzeus** [comment]
Have you tried putting the file in your snipe-it/public directory? Because that's where your web server should be pointing for hosting snipe-it.

**Comment by MariusTaz** [comment]
Hi kunzeus, yes I did. And it has exactly the same behaviour as described above. Any other suggestions?
Thank you in advance! 

PS. Tried with the latest version 6.0.9 and the same.

**Comment by revidm** [comment]
Having the same issue - doesn't matter what I try. 
Checked the logs and despite the file being there, it's showing the error previously mentioned and yet the webserver is seeing a request for /api/v1/companies

**Comment by justinkoby** [comment]
Instructions that I found were unclear. I had to go into Snipe, click on my name in the upper right, and generate an API key there. Then I used that key in the mobile app under the alternate config option.

**Comment by diegogarciadev** [comment]
Hello, have you solved the issue? I'm trying to solve all pending issues. Thanks

**Comment by MariusTaz** [comment]
Hello, Unfortunatelly no. Issue still persists. Thank you.

**Comment by diegogarciadev** [comment]
If you open the address https://snipeit.[myserver].com/snipeitapp_config.php in your browser, what can you see?

In the app, you have to write only **https://snipeit.[myserver].com**

**Comment by VinnyPolar** [comment]
When I open the link, the api key appears normally, but for some reason the app says it can't find anything at the address. If I just write https://snipeit.[myserver].com it doesn't work, I need to put a / right after it. So I solved this problem here
