### ISSUE TITLE
Improve user experience for non-technical users whilst setting up the app

### ISSUE THREAD

**Issue by proffalken** [diegogarciadev/android_snipeitapp_config#36]
**Is your feature request related to a problem? Please describe.**
Currently, when configuring the app, you need to generate an API key on the server, then copy that API key into a temporary file on the server, then configure the application.

This makes setup of the application only possible when someone with access to the filesystem is available, preventing users from being able to "self-serve" application setup.

**Describe the solution you'd like**
Instead of asking users to create files on the file system, an OAuth-like approach of "Log in via the app, allow access for the app, return to app front screen" would be fantastic.

**Describe alternatives you've considered**
N/A

**Additional context**
I was thinking that even if OAuth isn't available, perhaps the `snipeitapp_config.php` file could still request that users log in, and then automatically create an API Key in that user's account before returning it to the App.

This way the API key is only ever seen by the app, is only available from the website during app setup (thereby preventing the need to remember to delete the file), and as long as you name it something sensible like `snipeit-app-<username>-key` then it shouldn't conflict with anything else in the platform.

**Comment by diegogarciadev** [comment]
Hello, there is no posibility to create the API key in another way. And the API doesn't allow to login with credentials.
