### ISSUE TITLE
Trust Anchor for Certification Path Not Found

### ISSUE THREAD

**Issue by BoomCheeseBurge** [diegogarciadev/android_snipeitapp_config#37]
**Describe the bug**
On the previous day, I have installed and configured the Snipe-IT mobile to be connected to my Snipe-IT https website through the Snipe-IT's API token. The connection of the app configuration was successful without any issues. However, today, when I opened the Snipe-IT mobile application, every action I do I am met with this unfamiliar error.

However, when I tried to reinstall the mobile app and configure the app's connection to the Snipe-IT web app, the error is gone and everything works as it should. I am still curious as to what caused this error message on the mobile application?

**To Reproduce**
1. Configure the mobile app to be connected to the Snipe-IT web app through an API token and successfully connect them both.
2. Close the app and turn off phone and wait for a day.
3. The next day open the mobile app again.
4. Every data query related action within the app is met with this error.

**Expected behavior**
Whenever I click a button to query data from the Snipe-IT web app, an error message pop-up that states the following:

'-1 :java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.'

**Screenshots**
![image](https://github.com/diegogarciadev/android_snipeitapp_config/assets/80831628/0a261f76-7299-4e13-a9f7-fb691e36b727)

**Desktop (please complete the following information):**
 - OS: -
 - Browser: -
 - Version: -

**Smartphone (please complete the following information):**
 - Device: -
 - OS: -

**Additional context**

[UPDATE!]

Apparently, I found that it was a bug coming from enabling the SSL certificate verification feature in the mobile app.

![image](https://github.com/diegogarciadev/android_snipeitapp_config/assets/80831628/83c8eaf6-7e9f-4715-b092-1c75ad3aeb4f)

I switched it off and all features of the app works again without issue even if I close the mobile application or shut down my phone and open the application again.

**Comment by diegogarciadev** [comment]
That error means that you have a configuration issue in your webserver. Usually web breowsers skip the error. Yo need to check the intermediate certs to solve that problem.

Regards.
