### ISSUE TITLE
Edit option Error -1

### ISSUE THREAD

**Issue by Kamixss** [diegogarciadev/android_snipeitapp_config#39]
**Describe the bug**
After clicking on edit then scanning the asset tag and editing some info of the asset I'm getting error -1  http://IP/api/v1/hardware/3

**To Reproduce**
1. Go to 'Edit'
2. Scan the asset tag
3. Modify some info
4. Click Save

**Expected behavior**
Save the modified info of the asset

**Desktop (please complete the following information):**
 - OS: Android 13

**Smartphone (please complete the following information):**
 - Device: , Samsung s21 Ultra
 - OS: Android 13

**Comment by diegogarciadev** [comment]
It should be solved in the next version
