### ISSUE TITLE
java cert error

### ISSUE THREAD

**Issue by hafriz** [diegogarciadev/android_snipeitapp_config#4]
hi i try to setup as per documentation. but there is error as shown in screenshot. can you help me?
![Screenshot_2020-09-03-14-51-46-49](https://user-images.githubusercontent.com/1394343/92081482-b0f77800-edf5-11ea-9a61-94fd43338fe5.png)

**Comment by diegogarciadev** [comment]
Hello @hafriz , Let me check, I think I have to make a new version to avoid this problem. Keep connected.

**Comment by hafriz** [comment]
> Hello @hafriz , Let me check, I think I have to make a new version to avoid this problem. Keep connected.

Hi Diegogarcia, thanks will wait for your update. Thanks

**Comment by diegogarciadev** [comment]
Hello,

How about your cert, it's a self signed cert? Have you tried to use http instead? If myou have a public domain maybe you can use let's encrypt to get a certificate.

Allow https servers without cert validation is a high security risk. I think I can't do that...

Thank you.

**Comment by hafriz** [comment]
> Hello,
> 
> How about your cert, it's a self signed cert? Have you tried to use http instead? If myou have a public domain maybe you can use let's encrypt to get a certificate.
> 
> Allow https servers without cert validation is a high security risk. I think I can't do that...
> 
> Thank you.

Hi Diego, yes my server use a valid certificate issued by Sectigo. so the error i posted on the screenshot means that the certificate is not valid? then okay i try to check it first might be i wrongly setup the cert. 

THanks

**Comment by diegogarciadev** [comment]
Have you solve the issue? If cert doesn't work you have to try with http instead. Google is not allowing me to avoid cert validation as a security risk
