### ISSUE TITLE
Error 401: Unauthorized again :(

### ISSUE THREAD

**Issue by wkulesza** [diegogarciadev/android_snipeitapp_config#41]
**Describe the bug**
After upgrading Snipe-IT to 6.2.0 newest version and creating a new API key in keys, Error 401: Unauthorized shows up when configuring Snipe-It android app.

**To Reproduce**
1. Use Snipe-It 6.2.0 version
2. Generate Personal API Key in Snipe
3. Create snipeitapp_config.php file in /public folder (make sure it's accessible via browser), paste in your (long) api key in the place of "Enter your api key here!!" value
4. Open up Android app and go to Configure and provide your SSL-enabled url of snipe it location
5. Observe Error 401: Unauthorized

**Expected behavior**
App should respond with: "App configured!!"

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Snipe-It version 6.2.0

**Smartphone (please complete the following information):**
 - Device: Huawei Y5 2019
 - Android 9
 - snipeit app 0.7.5-SnipeIT

**Comment by diegogarciadev** [comment]
Try pasting the API key in alternative method. Take care with white spaces!
