### ISSUE TITLE
Serial Number Scanning Feature for Checkin and Out

### ISSUE THREAD

**Issue by ZettaWulf** [diegogarciadev/android_snipeitapp_config#42]
Wanted to throw in a request to be able to use the serial number feature to be used as well to check in and check out equipment. 

Sometimes users will pick or peel asset tags off devices, this feature would be greatly appreciated

**Comment by diegogarciadev** [comment]
Serial number search will be available in next release

**Comment by diegogarciadev** [comment]
Serial number search will be available in next release
