### ISSUE TITLE
Ability to remove logo

### ISSUE THREAD

**Issue by Xalvas** [diegogarciadev/android_snipeitapp_config#43]
Hi.
I was wondering if it were possible to add an option to remove the logo from the main screen, as for small screen devices, the logo pushes the buttons to the bottom of the screen, and it won't let me scroll the screen to show the cut-off buttons.

Either this, or the addition of a scroll bar?

Many thanks,
Ben

**Comment by diegogarciadev** [comment]
Solved in the next version
