### ISSUE TITLE
Configure app without uploading file?

### ISSUE THREAD

**Issue by ggiesen** [diegogarciadev/android_snipeitapp_config#6]
Would it be possible to provide a way to configure the app without having to upload the file? If all the app requires is the server address and the API key, would it be possible to just directly input the API key into the app instead?

We're currently using a hosted version of Snipe-IT, so even if Snipe-IT were willing to host the file for us, managing it as we add and remove users would be a royal pain.

**Comment by diegogarciadev** [comment]
Hello @ggiesen,

I can add this feature but I think its difficult to manage because api key has a lot of characters...

**Comment by ggiesen** [comment]
Yeah my expectation would be that someone would email themselves (or using some other method) the API key directly (or just log into their Snipe-IT instance from their mobile browser) and copy and paste the API key

**Comment by diegogarciadev** [comment]
Ok, I will implement it as soon as posible. Keep connected!

**Comment by diegogarciadev** [comment]
@ggiesen, a new beta version is about to reach Google Play, you can try it in a few hours. Join at https://play.google.com/apps/testing/com.diegogarciadev.assetsmanager.snipeit

**Comment by ggiesen** [comment]
I've tested it and it works. Closing the issue.

FYI I understand English is not your native language, the word "Scanner" in the app name is misspelled. It should have two "n"'s. Not sure if it can be changed. Thanks for making a great app!

**Comment by diegogarciadev** [comment]
> I've tested it and it works. Closing the issue.
> 
> FYI I understand English is not your native language, the word "Scanner" in the app name is misspelled. It should have two "n"'s. Not sure if it can be changed. Thanks for making a great app!

Thanks for your feedback. Yes, you're right, English is not my mother language. I will change the name in Google Play.

Regards.
